name: Java Build

on:
  pull_request:
    branches: ["main", "master"]
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["17", "21"]
    name: Java ${{ matrix.java }} Build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: <>-- Build --<>
        run: ./gradlew build createExe --no-daemon

      - name: <>-- Assemble --<>
        run: ./gradlew assembleGithubArtifacts --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: Executables
          path: publish/github
