name: Java Build

on:
  pull_request:
    branches: ["main", "master"]
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java Build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: <>-- Test --<>
        run: ./gradlew test

      - name: <>-- Create Windows Executables --<>
        run: ./gradlew createExe

      - name: <>-- Assemble --<>
        run: ./gradlew assembleGithubArtifacts

      - uses: actions/upload-artifact@v4
        with:
          name: Executables
          path: publish/github
